- name: Pull an image
  community.docker.docker_image_pull:
    name: "{{item}}"
  loop:
    - ahmedmfarouk/devops-mid-project:backend
    - ahmedmfarouk/devops-mid-project:frontend
    - ahmedmfarouk/devops-mid-project:postgres