.container_scanning:
  image:
    name: docker.io/aquasec/trivy:latest
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
    TRIVY_NO_PROGRESS: "true"
    TRIVY_CACHE_DIR: ".trivycache/"
  script:
    - trivy --version
    - trivy clean --scan-cache
    - time trivy image --download-db-only
    - mkdir -p .trivycache
    - time trivy image --input $TAR_IMAGE_NAME --exit-code 0 --format template --template "@/contrib/gitlab.tpl" --output "$FULL_IMAGE_NAME-scanning-report.json" "$FULL_IMAGE_NAME"
    - time trivy image --input $TAR_IMAGE_NAME --exit-code 0 "$FULL_IMAGE_NAME"
    - time trivy image --input $TAR_IMAGE_NAME --exit-code 1 --severity CRITICAL "$FULL_IMAGE_NAME"
  cache:
    paths:
      - .trivycache/
  artifacts:
    when: always
    reports:
      container_scanning: $FULL_IMAGE_NAME-scanning-report.json

stages:
  - notify
  - config
  - build
  - test
  - dockerization
  - security-scan
  - deploy

slack-notify:
  stage: notify
  script:
    - |
      curl -X POST -H 'Content-type: application/json' --data '{
        "text": ":drum_with_drumsticks: :drum_with_drumsticks: :drum_with_drumsticks:\n:rocket: NEW DEPLOYMENT :tada:\n\n
        Project: '"$CI_PROJECT_NAME"'\n
        Branch: '"$CI_COMMIT_REF_NAME"'\n
        Pipeline: <'"$CI_PIPELINE_URL"'|#'"$CI_PIPELINE_ID"'>\n
        Commit: <'"$CI_PROJECT_URL"'/-/commit/'"$CI_COMMIT_SHA"'|'"${CI_COMMIT_SHA:0:8}"'> - '"$CI_COMMIT_MESSAGE"'\n
        Deployed by '"$GITLAB_USER_NAME"'"
      }' $SLACK_WEBHOOK
      
config-deployment-machine:
  stage: config
  before_script:    
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    # to install required secure .pem file
    - apt install curl bash -y
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - cp .secure_files/gitlab-test.pem ~/.ssh/ec2_key.pem
    - chmod 600 ~/.ssh/ec2_key.pem
    # add ip address to /etc/hosts to change according to EC2_IP variable
    - echo "$EC2_IP    $EC2_HOSTNAME" |  tee -a /etc/hosts
    - cat /etc/hosts
    - ssh-keyscan -H $EC2_HOSTNAME >> ~/.ssh/known_hosts
    - apt-get update
    - apt install ansible-core -y
  script:
    - ansible-playbook site.yml -i inventory.ini --private-key=~/.ssh/ec2_key.pem
  only:
    - config_branch


build-backend:
  image: python:3.10
  stage: build
  script:
    - cd backend/
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  artifacts:
    paths:
      - backend/venv/
      - backend/src/
      - backend/requirements.txt
  only:
    - main

lint-backend:
  image: python:3.10
  stage: test
  script:
    - cd backend/
    - pip install flake8
    - source venv/bin/activate
    - flake8 src/
  needs: 
    - build-backend
  only:
    - main

test-backend:
  image: python:3.10
  stage: test
  services:
    - postgres
  variables:
    POSTGRES_HOST: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: microservices_db 
    POSTGRES_HOST_AUTH_METHOD: trust    
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/microservices_db"
    FLASK_ENV: "testing"
  script:
    - cd backend/
    - pip install pytest
    - source venv/bin/activate
    - pytest src/
  needs: 
    - build-backend
  only:
    - main

docker-build-backend:
  stage: dockerization
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd backend/
    - docker build -t $BACKEND_IMAGE .
    - cd ..
    - docker save $BACKEND_IMAGE -o backend-image.tar
  artifacts:
    paths:
      - backend-image.tar
  needs:
    - lint-backend
    - test-backend
  only:
    - main

trivy-backend:
  stage: security-scan
  extends: .container_scanning
  variables:
    TAR_IMAGE_NAME: backend-image.tar
    FULL_IMAGE_NAME: $BACKEND_IMAGE
  needs:
    - docker-build-backend
  only:
    - main


build-frontend:
  image: node:18
  stage: build
  script:
    - cd frontend/
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/build/
  cache:
    key: frontend-deps
    paths:
      - frontend/node_modules/
    policy: pull-push
  only:
    - main

lint-frontend:
  image: node:18
  stage: test
  script:
    - cd frontend/
    - npm install --save-dev eslint eslint-plugin-react eslint-plugin-react-hooks eslint-plugin-jsx-a11y @typescript-eslint/parser @typescript-eslint/eslint-plugin
    - npm run lint
  needs: 
    - build-frontend
  only:
    - main

test-frontend:
  image: node:18
  stage: test 
  script:
    - echo "Testing frontend ... "
  needs: 
    - build-frontend
  only:
    - main

docker-build-frontend:
  stage: dockerization
  image: docker:latest
  services:
    - docker:dind
  script:
    - ls frontend/ 
    - docker build -t $FRONTEND_IMAGE -f frontend/Dockerfile frontend/
    - docker save $FRONTEND_IMAGE -o frontend-image.tar
  artifacts:
    paths:
      - frontend-image.tar
  needs:
    - lint-frontend
    - test-frontend
  only:
    - main

trivy-frontend:
  stage: security-scan
  extends: .container_scanning
  variables:
    TAR_IMAGE_NAME: frontend-image.tar
    FULL_IMAGE_NAME: $FRONTEND_IMAGE
  needs:
    - docker-build-frontend
  only:
    - main


docker-build-postgres:
  stage: dockerization
  image: docker:latest
  services:
    - docker:dind
  script:
    - ls database/ 
    - docker build -t $POSTGRES_IMAGE -f database/Dockerfile database/
    - docker save $POSTGRES_IMAGE -o postgres-image.tar
  artifacts:
    paths:
      - postgres-image.tar
  only:
    - main

trivy-postgres:
  stage: security-scan
  extends: .container_scanning
  variables:
    TAR_IMAGE_NAME: postgres-image.tar
    FULL_IMAGE_NAME: $POSTGRES_IMAGE
  needs:
    - docker-build-postgres
  only:
    - main

docker-copy-images:
  stage: deploy
  image: docker:latest
  services: 
    - docker:dind
  before_script:    
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    # to install required secure .pem file
    - apk add curl bash 
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - cp .secure_files/gitlab-test.pem ~/.ssh/ec2_key.pem
    - chmod 600 ~/.ssh/ec2_key.pem
    # add ip address to /etc/hosts to change according to EC2_IP variable
    - echo "$EC2_IP    $EC2_HOSTNAME" |  tee -a /etc/hosts
    - cat /etc/hosts
    - ssh-keyscan -H $EC2_HOSTNAME >> ~/.ssh/known_hosts
  script:
    - scp -i ~/.ssh/ec2_key.pem frontend-image.tar $EC2_USERNAME@$EC2_HOSTNAME:~/frontend-image.tar
    - scp -i ~/.ssh/ec2_key.pem backend-image.tar $EC2_USERNAME@$EC2_HOSTNAME:~/backend-image.tar
    - scp -i ~/.ssh/ec2_key.pem postgres-image.tar $EC2_USERNAME@$EC2_HOSTNAME:~/postgres-image.tar
    - scp -i ~/.ssh/ec2_key.pem docker-compose.yml $EC2_USERNAME@$EC2_HOSTNAME:~/docker-compose.yml
    - ssh -i ~/.ssh/ec2_key.pem $EC2_USERNAME@$EC2_HOSTNAME "docker load -i frontend-image.tar"
    - ssh -i ~/.ssh/ec2_key.pem $EC2_USERNAME@$EC2_HOSTNAME "docker load -i backend-image.tar"
    - ssh -i ~/.ssh/ec2_key.pem $EC2_USERNAME@$EC2_HOSTNAME "docker load -i postgres-image.tar"
  needs:
    - trivy-frontend
    - trivy-backend
    - trivy-postgres
    - job: docker-build-frontend
      artifacts: true
    - job: docker-build-backend
      artifacts: true
    - job: docker-build-postgres
      artifacts: true
  only:
    - main

docker-compose:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind  
  before_script:    
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    # to install required secure .pem file
    - apk add curl bash 
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - cp .secure_files/gitlab-test.pem ~/.ssh/ec2_key.pem
    - chmod 600 ~/.ssh/ec2_key.pem
    # add ip address to /etc/hosts to change according to EC2_IP variable
    - echo "$EC2_IP    $EC2_HOSTNAME" |  tee -a /etc/hosts
    - cat /etc/hosts
    - ssh-keyscan -H $EC2_HOSTNAME >> ~/.ssh/known_hosts
  script:
    - ssh -i ~/.ssh/ec2_key.pem $EC2_USERNAME@$EC2_HOSTNAME "
      export FRONTEND_IMAGE='$FRONTEND_IMAGE';
      export BACKEND_IMAGE='$BACKEND_IMAGE';
      export POSTGRES_IMAGE='$POSTGRES_IMAGE';
      docker-compose down"
    - ssh -i ~/.ssh/ec2_key.pem $EC2_USERNAME@$EC2_HOSTNAME "
      export FRONTEND_IMAGE='$FRONTEND_IMAGE';
      export BACKEND_IMAGE='$BACKEND_IMAGE';
      export POSTGRES_IMAGE='$POSTGRES_IMAGE';
      docker-compose up -d"
  needs:
    - docker-copy-images
  when: manual
  only:
    - main