stages:          # List of stages for jobs, and their order of execution
  - config
  - notify
  - build
  - test
  - docker
  - deploy


image: python:3.10
build-backend:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - cd backend/
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  artifacts:
    paths:
      - venv/
      - src/
      - requirements.txt
  
lint-backend:
  stage: test
  script:
    - cd backend/
    - source venv/bin/activate
    - flake8 src/
  needs: 
    - build-backend

test-backend:
  stage: test
  script:
    - cd backend/
    - source venv/bin/activate
    - pytest src/
  needs: 
    - build-backend