- name: Installing docker
  hosts: all
  roles:
    - docker-install

- name: Docker login
  hosts: all
  roles:
    - docker-login

- name: Docker build
  hosts: buildingserver
  roles:
    - docker-build
    
- name: Docker push
  hosts: buildingserver
  roles:
    - docker-push

- name: Docker pull and run compose
  hosts: deploymentserver
  roles:
    - docker-pull
    - docker-deploy



    