- name: Copy docker files and sources (frontend)
  ansible.builtin.copy:
    src: "~/Desktop/devops/DevOps-Mid-Project/frontend/"
    dest: "~/Desktop/devops/DevOps-Mid-Project/frontend/"
    mode: preserve
  notify: Rebuild Docker frontend image

- name: Copy docker files and sources (backend)
  ansible.builtin.copy:
    src: "~/Desktop/devops/DevOps-Mid-Project/backend/"
    dest: "~/Desktop/devops/DevOps-Mid-Project/backend/"
    mode: preserve
  notify: Rebuild Docker backend image

- name: Copy docker files and sources (database)
  ansible.builtin.copy:
    src: "~/Desktop/devops/DevOps-Mid-Project/database/"
    dest: "~/Desktop/devops/DevOps-Mid-Project/database/"
    mode: preserve
  notify: Rebuild Docker database image

# - name: Build backend image 
#   community.docker.docker_image:
#     build:
#       nocache: true
#       path: ~/Desktop/devops/DevOps-Mid-Project/backend
#     name: ahmedmfarouk/backend:v1
#     source: build    
#     state: present

# - name: Build frontend image 
#   community.docker.docker_image:
#     build:
#       nocache: true
#       path: ~/Desktop/devops/DevOps-Mid-Project/frontend
#     name: ahmedmfarouk/frontend:v1
#     source: build    
#     state: present

# - name: Build database image
#   community.docker.docker_image:
#     build:
#       nocache: true
#       path: ~/Desktop/devops/DevOps-Mid-Project/database
#     name: ahmedmfarouk/postgres:v1
#     source: build    
#     state: present


# ---
# - name: Building and Pushing Docker Images
#   tasks:
#     - name: Copy docker files and sources (frontend)
#       ansible.builtin.copy:
#         src: "~/Desktop/devops/DevOps-Mid-Project/frontend/"
#         dest: "~/Desktop/devops/DevOps-Mid-Project/frontend/"
#         mode: preserve
#       notify: Rebuild Docker frontend image

#     - name: Copy docker files and sources (backend)
#       ansible.builtin.copy:
#         src: "~/Desktop/devops/DevOps-Mid-Project/backend/"
#         dest: "~/Desktop/devops/DevOps-Mid-Project/backend/"
#         mode: preserve
#       notify: Rebuild Docker backend image

#     - name: Copy docker files and sources (database)
#       ansible.builtin.copy:
#         src: "~/Desktop/devops/DevOps-Mid-Project/database/"
#         dest: "~/Desktop/devops/DevOps-Mid-Project/database/"
#         mode: preserve
#       notify: Rebuild Docker database image

#   handlers:
#     - name: Rebuild Docker backend image
#       community.docker.docker_image:
#         build:
#           nocache: true
#           path: "~/Desktop/devops/DevOps-Mid-Project/backend"
#           http_timeout: 0
#         name: ahmedmfarouk/devops-mid-project:backend
#         tag: version1
#         push: true
#         source: build
#         state: present
#         force: yes

#     - name: Rebuild Docker frontend image
#       community.docker.docker_image:
#         build:
#           nocache: true
#           path: "~/Desktop/devops/DevOps-Mid-Project/frontend"
#           http_timeout: 0
#         name: ahmedmfarouk/devops-mid-project:frontend
#         tag: version1
#         push: true
#         source: build
#         state: present
#         force: yes

#     - name: Rebuild Docker database image
#       community.docker.docker_image:
#         build:
#           nocache: true
#           path: "~/Desktop/devops/DevOps-Mid-Project/database"
#           http_timeout: 0
#         name: ahmedmfarouk/devops-mid-project:postgres
#         tag: version1
#         push: true
#         source: build
#         state: present
#         force: yes

# - name: Building frontend docker image
#   community.docker.docker_image_build:
#     name: mid-project-frontend
#     tag: "1"
#     path: ~/Desktop/devops/DevOps-Mid-Project/frontend

# - name: Building back docker image
#   community.docker.docker_image_build:
#     name: mid-project-backend
#     tag: "1"
#     path: ~/Desktop/devops/DevOps-Mid-Project/backend

# - name: Building database docker image
#   community.docker.docker_image_build:
#     name: mid-project-postgres
#     tag: "1"
#     path: ~/Desktop/devops/DevOps-Mid-Project/database
