version: '3.8'

services:
  frontend:
    container_name: frontend-app
    image: ahmedmfarouk/frontend:v1
    ports:
      - "8080:80"
    depends_on:
      - postgres
      - backend    
        
  backend:
    container_name: backend-app
    image: ahmedmfarouk/backend:v1
    ports:
      - "5000:5000"
    depends_on:
      - postgres


  postgres:
    container_name: postgres-container
    #addind directory with dockerfile to fix image vulnerabilities 
    image: ahmedmfarouk/postgres:v1
    #image: postgres:15-alpine
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: microservices_db    
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
